<?php // $Id$

/**
 * @file ting.module
 * Module to integrate the Ting search engine in our Drupal site.
 */

/**
 * Implementation of hook_menu().
 */
function ting_menu() {
  $path = drupal_get_path('module', 'ting') . '/includes';
  $items = array();

  $items['admin/settings/ting'] = array(
    'title' => 'Ting search',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ting.admin.inc',
    'file path' => $path,
  );

  return $items;
}

/**
 * Implementation of hook_search().
 */
function ting_search($op = 'search', $keys = null) {
  switch ($op) {
    case 'name':
      return t('Ting');

    case 'status':
    case 'admin':
      // We're not providing any sort of admin interface or status.
      return array();

    case 'search':
      if (function_exists('ting_search_add_js')) {
        // Loads the JavaScript we need from the Ting Search module.
        ting_search_add_js();
      }

      drupal_add_js(drupal_get_path('module', 'ting_search') . '/js/ting_search_result_page.js');
      drupal_add_js(array('tingSearch' => array(
        'result' => array(),
        'keys' => $keys,
        'ting_url' => url('ting/search/js'),
        'content_url' => url('ting/search/content/js'),
      	'result_template' => theme('ting_result')
      )), 'setting', 'footer');
      return array();
  }
}

