<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function production_site_menu() {
  $items = array();

  $items['admin/settings/production_site'] = array(
    'title' => 'Production site',
    'description' => 'Production site admin settings form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('production_site_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'production_site.admin.inc',
  );

  return $items;
}

/**
 * Preprocessor for page variables.
 *
 * Adds our dev-site warning to the end of messages. We do this
 * manually, since drupal_set_message on every page load causes problems
 * with AJAX calls and such things.
 */
function production_site_preprocess_page(&$variables) {
  $prod = production_site_detect();

  if (!$prod && $GLOBALS['user']->uid > 0) {
    $variables['messages'] .= '<div class="messages warning production-site">' . t('Currently working on development site. Changes made here will NOT appear on the live site and may be deleted or overwritten at any time.') . '</div>';
  }
}

/**
 * Helper function to detect if we're on a production site.
 */
function production_site_detect() {
  $whitelist = (bool) variable_get('production_site_list_type', FALSE);
  $name_str = trim(variable_get('production_site_hostnames', ''));

  if (!empty($name_str)) { 
    $names = preg_split('/[\r\n]+/', $name_str);
  }

  foreach ($names as $name) {
    if (strpos($_SERVER['HTTP_HOST'], $name) !== FALSE) {
      return ($whitelist) ? TRUE : FALSE;
    }
  }
  return ($whitelist) ? FALSE : TRUE;
}

