<?php
// $Id$

/**
 * @file ding_library_map.module
 * Displays library nodes on a map with additional information shown on mouse over
 */

/**
 * Implementation of hook_menu().
 */
function ding_library_map_menu() {
  $items = array();

  $items['admin/settings/ding_library_map'] = array(
    'title' => 'Library map',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_library_map_admin_settings_form'),
    'access arguments' => array('configure libraries'),
    'file' => 'ding_library_map.admin.inc',
  );

  return $items;
}

/**
 * Render the map output.
 */
function ding_library_map_display() {
  $module_path = drupal_get_path('module', 'ding_library_map');
  $map_id = 'library-map';
  drupal_add_css($module_path . '/css/ding_library_map.css');

  drupal_add_js(array('dingLibraryMap' => array(
    'fullDayNames' => array(
      'mon' => t('Monday'),
      'tue' => t('Tuesday'),
      'wed' => t('Wednesday'),
      'thu' => t('Thursday'),
      'fri' => t('Friday'),
      'sat' => t('Saturday'),
      'sun' => t('Sunday'),
    ),
    'shortDayNames' => array(
      'mon' => t('Mon'),
      'tue' => t('Tue'),
      'wed' => t('Wed'),
      'thu' => t('Thu'),
      'fri' => t('Fri'),
      'sat' => t('Sat'),
      'sun' => t('Sun'),
    ),
  )), 'setting', 'footer', TRUE);

  drupal_add_js($module_path . '/js/jquery.scrollTo/jquery.scrollTo-min.js');
  drupal_add_js($module_path . '/js/jquery.url/jquery.url.js');
  drupal_add_js($module_path . '/js/ding_library_map.js');

  $map = _ding_library_map_data();

  drupal_add_js('$(function() { Drupal.dingLibraryMap("' . $map['id'] . '", Drupal.settings.dingLibraryMap) });', 'inline');

  return '<div class="ding-library-map">' . theme('gmap', $map) . '</div>';
}

function ding_library_map_gmap($hook, &$map) {
	if ($hook == 'pre_theme_map') {
		foreach ($map['markers'] as $i => $marker) {
			//If the marker text contain no actual content then reset it to avoid normal behavior
			//e.g. showing an empty Google Map pop up
			if ($marker['text'] != '<div class="gmap-popup"></div>') {
				$map['marker'][$i]['text'] = NULL;
			}
		}
	}
}

/**
 * Helper function to generate map data.
 *
 * @TODO: This could do with a rewrite.
 */
function _ding_library_map_data() {
  $query = db_query("
    SELECT n.nid, n.title, l.street, l.city, l.postal_code, l.latitude, l.longitude
    FROM location AS l
    LEFT JOIN location_instance AS li ON (l.lid = li.lid)
    LEFT JOIN node AS n ON (li.vid = n.vid)
    LEFT JOIN ding_library dl ON (n.vid = dl.vid)
    WHERE (n.status <> 0) AND (n.type = 'library') AND
          (dl.library_show_on_map = 1);
  ");
  
	$libraries = array();
	while ($row = db_fetch_object($query)) {
		$libraries[$row->nid] = $row;
  }

  $oh_data = office_hours_bulk_load(implode(',', array_keys($libraries)), 'field_opening_hours');

  $map = array('id' => 'library-map', 'type' => 'map', 'zoom' => 12, 'minzoom' => 9, 'maxzoom' => 14, 'height' => '200px', 'width' => '100%', 'controltype' => 'Small', 'behavior' => array('extramarkerevents' => 1, 'nomousezoom' => 1));
  if ($center = variable_get('ding_library_map_center', false)) {
    $center = explode(',', $center, 2);
    $variables = array(0 => 'latitude', 1 => 'longitude');
    foreach ($variables as $index => $attribute) {
      if (isset($center[$index]) && is_numeric($center[$index])) {
        $map[$attribute] = trim($center[$index]);
      }
    }
  }

  // Add marker for each library.
  foreach ($libraries as $lib) {
    $status = (!empty($oh_data['data'][$lib->nid]['status'])) ? $oh_data['data'][$lib->nid]['status'] : 'closed';

    $map['markers'][] = array(
      'latitude' => $lib->latitude,
      'longitude' => $lib->longitude,
      'markername' => 'ding_library_map_' . $status,
      'name' => $lib->title,
      'street' => $lib->street,
      'city' => $lib->city,
      'postal-code' => $lib->postal_code,
      'opening_hours' => $oh_data['data'][$lib->nid]['week'],
      'state' => $status,
      'url' => url('node/' . $lib->nid, array('absolute' => TRUE)),
      'text' => FALSE
    );
  }

  return $map;
}

