<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function similarterms_preview_menu() {
  $items = array();

  $items['similarterms/preview/js'] = array(
    'page callback' => 'similarterms_preview_page_ahah',
    'file' => 'similarterms_preview.pages.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function similarterms_preview_perm() {
  return array('preview similar content by terms');
}

/**
 * Implementation of hook_form_alter().
 */
function similarterms_preview_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] == 'node-form' && user_access('preview similar content by terms')) {
    // Provide a settings list of tagging vocabularies and a callback URL.
    drupal_add_js(array('similartermsPreview' => array(
      'callback' => url('similarterms/preview/js'),
      'taggingVocabularies' => array_keys($form['taxonomy']['tags']),
    )), 'setting');

    drupal_add_js(drupal_get_path('module', 'similarterms_preview') . '/similarterms_preview.node-form.js');
  }
}

