<?php
// $Id: google404.module,v 1.1 2009/08/31 10:52:06 mikl Exp $

/**
 * Implementation of hook_menu().
 */
function google404_menu() {
  $items = array();

  $items['google404'] = array(
    'title' => 'Page not found (404)',
    'page callback' => 'google404_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/settings/google404'] = array(
    'title' => 'Google 404',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google404_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'google404.admin.inc',
  );

  return $items;
}

/**
 * Our 404 page callback.
 */
function google404_page() {
  drupal_add_js(<<<JAVASCRIPT
var GOOG_FIXURL_LANG = '{$GLOBALS['language']->language}';
var GOOG_FIXURL_SITE = '{$_SERVER['HTTP_HOST']}'
JAVASCRIPT
  , 'inline');
  $message = check_markup(variable_get('google404_message', t('Sorry, the page you were looking for could not be found.'), variable_get('google404_message_format', FILTER_FORMAT_DEFAULT)));
  $js = '<script type="text/javascript" src="http://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js" defer="defer"></script>';
  return $message . $js;
}

