<?php
// $Id$

/**
 * @file ding_breadcrumbs.module
 * Handles the generation and loading of nodes from "slugs", 
 * small bits of text, suitable for use in URLs.
 */

/**
 * Implementation of hook_nodeapi().
 */
function ding_breadcrumbs_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // Only on viewing a full node on a page by itself.
  if ($op == 'view' && !$a3 && $a4) {
    $trail = array(
      l(t('Home'), '<front>'),
    );

    if ($node->type == 'library') {
      $trail[] = l('Libraries', 'biblioteker');
    }
    else {
      if (isset($node->field_library_ref[0]['nid'])) {
        $trail[] = l('Libraries', 'biblioteker');
        $library = node_load($node->field_library_ref[0]['nid']);
        $trail[] = l($library->title, 'node/' . $library->nid);

        if ($node->type == 'article') {
          $trail[] = l(t('Blog'), 'biblioteker/' . $library->ding_slug . '/blog');
        }
        elseif ($node->type == 'event') {
          $trail[] = l(t('Events'), 'biblioteker/' . $library->ding_slug . '/arrangementer');
        }
      }
    }
    $trail[] = $node->title;
      
    drupal_set_breadcrumb($trail);
  }
}

/**
 * Set breadcrumbs for library-related pages.
 *
 * @param object $library
 *    The library node.
 */
function ding_breadcrumbs_set_library($library) {
  $path_copy = $path = arg(); // Get all URL components from Drupal's arg function.

  $trail = array(
    l(t('Home'), '<front>'),
    l('Libraries', array_shift($path_copy)),
  );

  // Lets take all the path components before the last one.
  while (count($path_copy) > 1) {
    $piece = array_shift($path_copy);
    $index = array_search($piece, $path);
    if ($index == 1) {
      $trail[] = l($library->title, 'node/' . $library->nid);
    }
    else {
      $trail[] = l(implode(_ding_breadcrumbs_get_name($path, $piece, $index), '/', array_slice($path, 0, $index)));
    }
  }

  // For the last component, we do mostly the same, besides the link.
  $piece = array_shift($path_copy);
  $index = array_search($piece, $path);
  if ($index == 1) {
    $trail[] = $library->title;
  }
  else {
    $trail[] = _ding_breadcrumbs_get_name($path, $piece, $index);
  }

  drupal_set_breadcrumb($trail);
}

/**
 * Try to figure out the real name of a path component.
 */
function _ding_breadcrumbs_get_name($path, $piece, $index) {
  if ($index == 2) {
    return drupal_ucfirst($piece);
  }
  return t('Unknown');
}

