<?php
// $Id$

/**
 * @file alma.module
 * Drupal module implementing Axiell ABs Alma API.
 */

/**
 * Implementation of hook_menu().
 */
function alma_menu() {
  $items = array();

  $items['admin/settings/alma'] = array(
    'title' => 'Axiell Alma',
    'description' => 'Settings for the Alma module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alma_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'alma.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_requirements().
 */
function alma_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break at install time.
  $t = get_t();

  if (!function_exists('simplexml_load_string')) {
    $requirements['simplexml'] = array(
      'title' => 'SimpleXML',
      'description' => $t('The Alma module requires SimpleXML to function. Please install and/or enable SimpleXML in your PHP configuration.'),
      'severity' => REQUIREMENT_ERROR,
    );
  }

  return $requirements;
}

/**
 * Get data from Alma.
 *
 * @param string $method
 *    The method on to call om the Alma server, e.g. 'patron/status'
 * @param array $params
 *    Array of parameters for the request. borrCard and pinCode is required
 *    for all request related to library patrons.
 * @return mixed
 *    FALSE on error, otherwise a SimpleXML object with the response.
 */
function alma_request($method, $params) {
  $base_url = variable_get('alma_base_url', '');

  if (empty($base_url)) {
    trigger_error(t('alma_request() called, but "alma_base_url" is empty. Please set this on the Alma settings page.'), E_USER_ERROR);
    return FALSE;
  }

  $request = drupal_http_request(url($base_url . $method, array('query' => $params)));

  if ($request->code == 200) {
    $sx = simplexml_load_string($request->data);
    return $sx;
  }
  return FALSE;
}

