<?php
// $Id$

/**
 * @file alma.module
 * Drupal module implementing Axiell ABs Alma API.
 */

/**
 * Implementation of hook_menu().
 */
function alma_menu() {
  $items = array();

  $items['admin/settings/alma'] = array(
    'title' => 'Axiell Alma',
    'description' => 'Settings for the Alma module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alma_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'alma.admin.inc',
  );

  $items['admin/settings/alma/main'] = array(
    'title' => 'Alma',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_requirements().
 */
function alma_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break at install time.
  $t = get_t();

  if (!function_exists('simplexml_load_string')) {
    $requirements['simplexml'] = array(
      'title' => 'SimpleXML',
      'description' => $t('The Alma module requires SimpleXML to function. Please install and/or enable SimpleXML in your PHP configuration.'),
      'severity' => REQUIREMENT_ERROR,
    );
  }

  return $requirements;
}

/**
 * Return a fully instantiated AlmaClient instance.
 */
function alma_client() {
  // This is basically a singleton. We also wait until right before
  // instantiating to include our required classes. That seems like a
  // decent performance tradeoff instead of loading everything on every
  // page load.
  static $client;
  if (!isset($client)) {
    $path = drupal_get_path('module', 'alma');
    include($path . '/lib/AlmaClient/AlmaClient.class.php');
    $client = new AlmaClient(variable_get('alma_base_url', ''));
  }
  return $client;
}

/**
 * Get list of library branches.
 *
 * @return array
 *    Array of branch names, keyed by their ID.
 */
function alma_client_get_branches() {
  static $branches;

  if (!isset($branches)) {
    if ($cache = cache_get('alma_branches') && !empty($cache->data)) {
      $branches = $cache->data;
    }
    else {
      try {
        $branches = alma_client()->get_branches();
        cache_set('alma_branches', $branches, 'cache', 1800);
      } catch (Exception $e) {
        return array();
      }
    }
  }
  return $branches;
}

/**
 * Get list of library branches where patrons can fetch their reservations.
 */
function alma_client_get_reservation_branches() {
  try {
    return alma_client()->get_reservation_branches();
  } catch (Exception $e) {
    return array();
  }
}

/**
 * Get information about a library patron.
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @return array
 *    The patron information as an array.
 */
function alma_client_get_patron_info($borr_card, $pin_code) {
  try {
    return alma_client()->get_patron_info($borr_card, $pin_code);
  }
  catch (AlmaClientBorrCardNotFound $e) {
    watchdog('alma_user', 'get_patron_info error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
  }
  catch (Exception $e) {
    drupal_set_message(t('An error occurred while trying to communicate with the library system. Please try again'), 'error', FALSE);
    watchdog('alma_user', 'get_patron_info error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Get a patron's reservations
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @return array
 *    The reservations as an array.
 */
function alma_client_get_reservations($borr_card, $pin_code) {
  try {
    return alma_client()->get_reservations($borr_card, $pin_code);
  } catch (Exception $e) {
    watchdog('alma_user', 'get_reservations error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Get a patron's loans
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @return array
 *    The loans as an array.
 */
function alma_client_get_loans($borr_card, $pin_code) {
  try {
    return alma_client()->get_loans($borr_card, $pin_code);
  } catch (Exception $e) {
    watchdog('alma_user', 'get_loans error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Get a patron's debts
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @return array
 *    The loans as an array.
 */
function alma_client_get_debts($borr_card, $pin_code) {
  try {
    return alma_client()->get_debts($borr_card, $pin_code);
  } catch (Exception $e) {
    watchdog('alma_user', 'get_debts error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Add reservation.
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's current four digit PIN code.
 * @param array $reservation
 *    Data for the reservation we're adding.
 */
function alma_client_add_reservation($borr_card, $pin_code, $reservation) {
  try {
    return alma_client()->add_reservation($borr_card, $pin_code, $reservation);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'add_reservation error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Change a reservation
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param array $reservation
 *    Data for the reservation we're changing.
 * @param array $changes
 *    Array of changes to apply.
 */
function alma_client_change_reservation($borr_card, $pin_code, $reservation, $changes) {
  try {
    return alma_client()->change_reservation($borr_card, $pin_code, $reservation, $changes);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'change_reservation error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Remove a reservation
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param array $reservation
 *    Data for the reservation we're removing.
 */
function alma_client_remove_reservation($borr_card, $pin_code, $reservation) {
  try {
    return alma_client()->remove_reservation($borr_card, $pin_code, $reservation);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'remove_reservation error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Renew a loan
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param array $loan_ids
 *    IDs for the loans we want renewed.
 */
function alma_client_renew_loan($borr_card, $pin_code, $loan_ids) {
  try {
    return alma_client()->renew_loan($borr_card, $pin_code, $loan_ids);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'renew_loan error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Add phone number
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param integer $number
 *    New phone number.
 * @param boolean $sms
 *    If TRUE, the number can be used for SMS.
 */
function alma_client_add_phone_number($borr_card, $pin_code, $number, $sms = TRUE) {
  try {
    return alma_client()->add_phone_number($borr_card, $pin_code, $number, $sms);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'add_phone_number error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Change phone number
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param string $number_id
 *    The phone number ID. Usually the phone number itself.
 * @param integer $new_number
 *    New phone number.
 * @param boolean $sms
 *    If TRUE, the number can be used for SMS.
 */
function alma_client_change_phone_number($borr_card, $pin_code, $number_id, $new_number, $sms = TRUE) {
  try {
    return alma_client()->change_phone_number($borr_card, $pin_code, $number_id, $new_number, $sms);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'change_phone_number error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Remove phone number
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param string $number_id
 *    The phone number ID. Usually the phone number itself.
 */
function alma_client_remove_phone_number($borr_card, $pin_code, $number_id) {
  try {
    return alma_client()->remove_phone_number($borr_card, $pin_code, $number_id);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'remove_phone_number error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Add e-mail address
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param integer $new_email
 *    New e-mail address.
 */
function alma_client_add_email_address($borr_card, $pin_code, $new_email) {
  try {
    return alma_client()->add_email_address($borr_card, $pin_code, $new_email);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'add_email_address error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Change e-mail address
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param integer $email_id
 *    The e-mail address ID. Usually the e-mail address itself.
 * @param integer $new_email
 *    New e-mail address.
 */
function alma_client_change_email_address($borr_card, $pin_code, $email_id, $new_email) {
  try {
    return alma_client()->change_email_address($borr_card, $pin_code, $email_id, $new_email);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'change_email_address error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Remove e-mail address
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's four digit PIN code.
 * @param string $email_id
 *    The e-mail address ID. Usually the e-mail address itself.
 */
function alma_client_remove_email_address($borr_card, $pin_code, $email_id) {
  try {
    return alma_client()->remove_email_address($borr_card, $pin_code, $email_id);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'remove_email_address error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

/**
 * Change PIN code.
 *
 * @param string $borr_card
 *    Library patron's borrowing card number. Either just an arbitrary
 *    number printed on their library card or their CPR-code.
 * @param string $pin_code
 *    Library patron's current four digit PIN code.
 * @param string $new_pin
 *    Library patron's new four digit PIN code.
 */
function alma_client_change_pin($borr_card, $pin_code, $new_pin) {
  try {
    return alma_client()->change_pin($borr_card, $pin_code, $new_pin);
  }
  catch (Exception $e) {
    watchdog('alma_user', 'change_pin error: “@message”', array('@message' => $e->getMessage(), WATCHDOG_ERROR));
    return FALSE;
  }
}

