<?php
// $Id$

/**
 * @file ting_search_autocomplete.module
 * Performs autocomplete for the Ting search box.
 */

/**
 * Implementation of hook_theme().
 */
function ting_search_autocomplete_theme() {
  return array();
}

/**
 * Implementation of hook_menu().
 */
function ting_search_autocomplete_menu() {
  $items = array();

  $items['ting/autocomplete/js'] = array(
    'title' => 'Ting search autocomplete',
    'description' => 'Returns a list of suggestions to use for autocompletion',
    'access arguments' => array('search content'),
    'page callback' => 'ting_search_autocomplete_js',
    'type' => MENU_CALLBACK,
    'file' => 'ting_search_autocomplete.pages.inc',
  );
  
  return $items;
}

function ting_search_autocomplete_form_ting_search_form_alter(&$form, &$form_state) {
	$form['keys']['#autocomplete_path'] = 'ting/autocomplete/js'; 
}