<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function ding_user_menu() {
  $items = array();

  $items['admin/user/ding_user'] = array(
    'title' => 'Ding! user settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_user_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_user.admin.inc',
  );

  $items['user/%user/change_pass'] = array(
    'title' => 'Change password',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_user_forms_change_pass', 1),
    'access callback' => 'ding_user_forms_access',
    'access arguments' => array('change_pass', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'ding_user.forms.inc',
  );

  return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function ding_user_menu_alter(&$items) {
  // Change the password recovery page to be a callback, not shown in menus.
  $items['user/password']['type'] = MENU_CALLBACK;

  // Change the title of the view profile tab.
  $items['user/%user/view']['title'] = 'Profile';

  // Hide the edit user tab.
  $items['user/%user_category/edit']['type'] = MENU_CALLBACK;
}

/**
 * Implementation of hook_user().
 */
function ding_user_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'form':
      $form = array();

      if ($account->has_secure_role || user_access('administer users'))  {
        $form['account']['display_name'] = array(
          '#type' => 'textfield',
          '#title' => t('Display name'),
          '#description' => t('Profile name as presented to the site users. Library transactions will still use your full name as provided by CPR.'),
          '#required' => TRUE,
          '#default_value' => $account->display_name,
          '#weight' => -1,
        );
      }
      return $form;
    case 'register':
      $form = array();

      $form['display_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Display name'),
        '#description' => t('Profile name as presented to the site users. Library transactions will still use your full name as provided by CPR.'),
        '#required' => TRUE,
        '#default_value' => $account->display_name,
        '#weight' => -11,
      );

      return $form;
    case 'insert':
      db_query("INSERT INTO {ding_user} (uid, pass, display_name) VALUES (%d, '%s', '%s');", $account->uid, user_hash_password($edit['pass']), check_plain($edit['display_name']));

      // According to hook_user docs, we should set the values we save
      // to NULL.
      $edit['display_name'] = NULL;
      break;
    case 'update':
      if (isset($edit['display_name']) && !is_null($edit['display_name'])) {
        if ($account->secure_pass === FALSE) {
          db_query("INSERT INTO {ding_user} (uid, display_name) VALUES (%d, '%s');", $account->uid, check_plain($edit['display_name']));
        }
        elseif ($account->display_name != $edit['display_name']) {
          db_query("UPDATE {ding_user} SET display_name = '%s' WHERE uid = %d;", check_plain($edit['display_name']), $account->uid);
        }

        // According to hook_user docs, we should set the values we save
        // to NULL.
        $edit['display_name'] = NULL;
      }
      break;
    case 'load':
      if ($account->uid) {
        if ($account->uid == 1 || ding_user_has_secure_role($account)) {
          $account->has_secure_role = TRUE;
        }
        else {
          $account->has_secure_role = FALSE;
        }

        $ding_user_data = db_fetch_array(db_query("SELECT pass, display_name FROM {ding_user} WHERE uid = %d LIMIT 1;", $account->uid));

        if ($ding_user_data) {
          $account->secure_pass = $ding_user_data['pass'];
          $account->display_name = $ding_user_data['display_name'];
        }
        else {
          // secure_pass = FALSE indicates that user doesn't have a row
          // in {ding_user}.
          $account->secure_pass = FALSE;
        }
      }
      break;
    case 'delete':
      db_query('DELETE FROM {ding_user} WHERE uid=%d', $account->uid);
      break;
    case 'view':
      if (isset($account->display_name) && !empty($account->display_name)) {
        drupal_set_title(check_plain($account->display_name));
      }
      $account->name = $account->display_name;

      break;
  }
}

/**
 * Implementation of hook_perm().
 */
function ding_user_perm() {
  return array(
    'change other user’s passwords',
  );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ding_user_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Alter the login form to disable the standard Drupal username/password
 * combination and provide our own fields instead.
 */
function ding_user_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      // If we have secure pages enabled, redirect login posts to SSL.
      if (function_exists('securepages_init')) {
        $form['#action'] = 'https://' . $_SERVER['HTTP_HOST'] . url($_GET['q'], array('query' => drupal_get_destination()));
      }

      // Replace Drupal's standard user/pass authentication with our own.
      $key = array_search('user_login_authenticate_validate', $form['#validate']);
      $form['#validate'][$key] = 'ding_user_login_validate';

      // Remove the standard user login links.
      unset($form['links']);
      break;
    case 'user_profile_form':
      $account = $form['_account']['#value'];

      // Remove or hide the standard user account settings we don't need.
      $form['account']['pass']['#type'] = 'value';

      if (!$account->has_secure_role) {
        $form['account']['name']['#type'] = 'value';
        $form['account']['name']['#value'] = $account->name;
      }
      else {
        // Add link to change admin password
        $form['change_password_link'] = array(
          '#value' => l('Change admin password', 'user/' . $form['_account']['#value']->uid . '/change_pass'),
        );
      }

      // Move the standard account controls down a bit.
      if (isset($form['account']['status'])) {
        $form['account']['status']['#weight'] = 1;
      }

      if (isset($form['account']['roles'])) {
        $form['account']['roles']['#weight'] = 1;
      }
      break;
    case 'comment_form':
      $account = user_load($GLOBALS['user']->uid);
      $form['_author']['#value'] = (!empty($account->display_name)) ? $account->display_name : $account->name;
      break;
  }
}

/**
 * User login validation.
 *
 * Serves as a replacement of user_login_authenticate_validate, using 
 * our own password table instead of Drupal's user table.
 */
function ding_user_login_validate($form, &$form_state) {
  if (empty($form_state['values']['name']) || empty($form_state['values']['pass'])) {
    // empty user name or password makes little sense to try and validate.
    return;
  }

  $account = user_load(array('name' => $form_state['values']['name'], 'status' => 1));

  if ($account && ding_user_check_password($form_state['values']['pass'], $account)) {
    global $user;
    $user = $account;
    user_authenticate_finalize($form_state['values']);
  }
}

/**
 * Helper function to check if user has a secure role.
 *
 * @param object $account
 *    A Drupal user object.
 * @return boolean
 *    Boolean indicating that user has a secure role.
 */
function ding_user_has_secure_role($account) {
  return array_intersect_key($account->roles, variable_get('ding_user_secure_roles', array()));
}

/**
 * Access control for the forms we provide.
 *
 * @param string $name
 *    The form name.
 * @param object $account
 *    The user account.
 * @return boolean
 *    If access was allowed.
 */
function ding_user_forms_access($name, $account) {
  switch ($name) {
    case 'change_pass':
      // Only accounts with a secure role have admin passwords.
      if ($account->uid != 1 && !$account->has_secure_role) {
        return FALSE;
      }
      // Everyone is allowed to change their own password.
      elseif ($GLOBALS['user']->uid == $account->uid) {
        return TRUE;
      }
      // Users with the right permissions is allowed to change the
      // password for anyone but uid=1.
      elseif ($account->uid != 1 && user_access('change other user’s passwords')) {
        return TRUE;
      }
      break;
  }
}

/**
 * Check whether a plain text password matches a stored hashed password.
 *
 * Reimplementation of Drupal 7's user_check_password.
 *
 * @param string $password
 *    A plain-text password
 * @param object $account
 *    A user object with at least the secure_pass value.
 * @return boolean
 *    TRUE or FALSE.
 */
function ding_user_check_password($password, $account) {
  $hash = _password_crypt($password, $account->secure_pass);
  return ($hash && $account->secure_pass == $hash);
}

