<?php
// $Id$

/**
 * @file ting_search.module
 * Displays facet browser and search results from the Ting database.
 */

/**
 * Implementation of hook_theme().
 */
function ting_search_theme() {
  return array(
    'ting_search_result_page' => array(
      'arguments' => array('keys' => NULL),
      'template' => 'ting_search_result_page'
    ),
    'ting_search' => array(
      'arguments' => array('result' => NULL),
      'template' => 'ting_search'
    ),
    'ting_result' => array(
      'arguments' => array('record' => NULL),
      'template' => 'ting_result'
    ),
    'ting_result_pager' => array(
      'arguments' => array('record' => NULL),
      'template' => 'ting_result_pager'
    ),
    'ting_search_collection' => array(
      'arguments' => array('collection' => NULL),
      'template' => 'ting_search_collection'
    ),
    'ting_facet_browser' => array(
      'arguments' => array('result' => NULL),
      'function' => 'ting_search_facet_browser'
    ),
    'ting_collection' => array(
      'arguments' => array('collection' => NULL),
      'template' => 'ting_collection',
      'file' => 'ting_search.theme.inc',
    ),
    'ting_object' => array(
      'arguments' => array('object' => NULL),
      'template' => 'ting_object'
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function ting_search_menu() {
  $items = array();

  $items['ting/search/js'] = array(
    'title' => 'Ting search results',
    'description' => 'Lists facets and search results from the Ting database as HTML or JSON.',
    'access arguments' => array('search content'),
    'page callback' => 'ting_search_pages_ting_js',
    'type' => MENU_CALLBACK,
    'file' => 'ting_search.pages.inc',
  );
  $items['ting/search/content/js'] = array(
    'title' => 'Content search AJAX page callback',
    'page callback' => 'ting_search_pages_content_js',
    'access arguments' => array('search content'),
    'type' => MENU_CALLBACK,
    'file' => 'ting_search.pages.inc',
  );
  $items['ting/collection'] = array(
    'title' => 'Display a collection of objects from the Ting database',
    'page callback' => 'ting_collection',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'ting_search.pages.inc',
  );
  $items['ting/object'] = array(
    'title' => 'Display a single object from the Ting database',
    'page callback' => 'ting_object',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'ting_search.pages.inc',
  );
  
  return $items;
}

/**
 * Implementation of hook_block().
 */
function ting_search_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
        array(
          'info' => t('Ting search box – for page header'),
          'cache' => BLOCK_NO_CACHE,
        ),
      );
    case 'view':
      return array(
        'subject' => t('Search'),
        'content' => drupal_get_form('ting_search_form'),
      );
  }
}

/**
 * Implementation of hook_menu_alter().
 */
function ting_search_menu_alter(&$items) {
  // Override the page callback for the Ting search results.
  $items['search/ting/%menu_tail']['page callback'] = 'ting_search_pages_result';
  $items['search/ting/%menu_tail']['file'] = 'ting_search.pages.inc';
  $items['search/ting/%menu_tail']['file path'] = drupal_get_path('module', 'ting_search');
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ting_search_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function ting_search_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Load Ting search interface JavaScript dependencies.
 */
function ting_search_add_js() {
	$basePath = drupal_get_path('module', 'ting');
  //Add Pure JS templating engine
  drupal_add_js($basePath . '/js/pure/js/pure.js', 'module', 'footer', TRUE);
	
	
	$path = drupal_get_path('module', 'ting_search');
  //Add base Prototype files for enhanced OOP
  drupal_add_js($path . '/js/prototype/object.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/prototype/enumerable.js', 'module', 'footer', TRUE);
  //drupal_add_js($path . '/js/pure/js/purePacked.js', 'module', 'footer', TRUE);

  //Add jQuery Url plugin
  drupal_add_js($path . '/js/jquery.url/jquery.url.js', 'module', 'footer', TRUE);
  //drupal_add_js($path . '/js/jquery.url/jquery.url.packed.js', 'module', 'footer', TRUE);

  drupal_add_js($path . '/js/ting_search.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/ting_search_result_page.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/ting_result.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/ting_facet_browser.js', 'module', 'footer', TRUE);
  drupal_add_css($path . '/css/ting_facet_browser.css', 'module');

  drupal_add_js(array('tingResult' => array(
                      'collectionTemplate' => ting_search_render_search_collection_template(),
                      'pagerTemplate' => ting_search_render_pager_template(),
                      'resultsPerPage' => 10,
                      'pagesInPager' => 5,
                      'resizeButtonText' => t('Show more facet terms'))),
                'setting');
}

function ting_search_render_search_collection_template() {
  module_load_include('php', 'ting', 'lib/ting-dbc-php5-client/lib/TingClient');
  
  $object = new TingClientObject();
  $object->id = 'id';

  $data = new TingClientDublinCoreData();
  foreach ($data as $attribute => $value) {
    $data->$attribute = array($attribute);
  }
  $object->data = $data;

  $collection = new TingClientObjectCollection(array($object));

  return theme('ting_search_collection', $collection);
}

function ting_search_render_pager_template() {
  return theme('ting_result_pager');
}

/**
 * Define our own search form.
 *
 * We were having problems with search_form from search.module, so
 * here's a very basic copy of it.
 */
function ting_search_form(&$form_state) {
  $form = array('#action' => url('search/ting'));

  $form['keys'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter your search terms here'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 255,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );

  return $form;
}

/**
 * Process a search form submission.
 */
function ting_search_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'search/ting/' . trim($form_state['values']['keys']);
}

