<?php
// $Id$

/**
 * @file ting_search.module
 * Displays facet browser and search results from the Ting database.
 */

/**
 * Implementation of hook_theme().
 */
function ting_search_theme() {
  return array(
    'ting_search_result_page' => array(
      'arguments' => array(),
      'template' => 'ting_search_result_page'
    ),
    'ting_search' => array(
      'arguments' => array('result' => NULL),
      'template' => 'ting_search'
    ),
    'ting_result' => array(
      'arguments' => array('record' => NULL),
      'template' => 'ting_result'
    ),
    'ting_result_pager' => array(
      'arguments' => array('record' => NULL),
      'template' => 'ting_result_pager'
    ),
    'ting_record' => array(
      'arguments' => array('record' => NULL),
      'template' => 'ting_record'
    ),
    'ting_facet_browser' => array(
      'arguments' => array('result' => NULL),
      'function' => 'ting_search_facet_browser'
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function ting_search_menu() {
  $items = array();

  $items['ting/search/js'] = array(
    'title' => 'Ting search results',
    'description' => 'Lists facets and search results from the Ting database as HTML or JSON.',
    'access arguments' => array('search content'),
    'page callback' => 'ting_search_pages_ting_js',
    'type' => MENU_CALLBACK,
    'file' => 'ting_search.pages.inc',
  );
  $items['ting/search/content/js'] = array(
    'title' => 'Content search AJAX page callback',
    'page callback' => 'ting_search_pages_content_js',
    'access arguments' => array('search content'),
    'type' => MENU_CALLBACK,
    'file' => 'ting_search.pages.inc',
  );

  return $items;
}

/**
 * Implementation of hook_block().
 */
function ting_search_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
        'searchbox' => array(
          'info' => t('Ting search box'),
          'cache' => BLOCK_CACHE_GLOBAL,
        ),
      );
    case 'view':
      return array(
        'subject' => t('Search'),
        'content' => drupal_get_form('search_form', '', '', 'ting', 'Skriv dit søgeord her'),
      );
  }
}

/**
 * Implementation of hook_menu_alter().
 */
function ting_search_menu_alter(&$items) {
  // Override the page callback for the Ting search results.
  $items['search/ting/%menu_tail']['page callback'] = 'ting_search_pages_result';
  $items['search/ting/%menu_tail']['file'] = 'ting_search.pages.inc';
  $items['search/ting/%menu_tail']['file path'] = drupal_get_path('module', 'ting_search');
}

/**
 * Load Ting search interface JavaScript dependencies.
 */
function ting_search_add_js() {
  $path = drupal_get_path('module', 'ting_search');
  //Add base Prototype files for enhanced OOP
  drupal_add_js($path . '/js/prototype/object.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/prototype/enumerable.js', 'module', 'footer', TRUE);

  //Add Pure JS templating engine
  drupal_add_js($path . '/js/pure/js/pure.js', 'module', 'footer', TRUE);
  //drupal_add_js($path . '/js/pure/js/purePacked.js', 'module', 'footer', TRUE);

  //Add jQuery Url plugin
  drupal_add_js($path . '/js/jquery.url/jquery.url.js', 'module', 'footer', TRUE);
  //drupal_add_js($path . '/js/jquery.url/jquery.url.packed.js', 'module', 'footer', TRUE);

  drupal_add_js($path . '/js/ting_search.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/ting_search_result_page.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/ting_result.js', 'module', 'footer', TRUE);
  drupal_add_js($path . '/js/ting_facet_browser.js', 'module', 'footer', TRUE);
  drupal_add_css($path . '/css/ting_facet_browser.css', 'module');

  drupal_add_js(array('tingResult' => array(
                      'recordTemplate' => ting_search_render_record_template(),
                      'pagerTemplate' => ting_search_render_pager_template(),
                      'resultsPerPage' => 10,
                      'pagesInPager' => 5,
                      'resizeButtonText' => t('Show more facet terms'))),
                'setting');
}

function ting_search_render_record_template() {
  module_load_include('php', 'ting', 'lib/ting-dbc-php5-client/lib/TingClient');
  $record = new TingClientRecord();
  $record->id = 'id';

  $data = new TingClientDublinCoreData();
  foreach ($data as $attribute => $value) {
    $data->$attribute = array($attribute);
  }
  $record->data = $data;

  return theme('ting_record', $record);
}

function ting_search_render_pager_template() {
  return theme('ting_result_pager');
}
